Schema

 - Matches:
     - MatchId: int
         - MatchWeek: int
         - HomeTeam: int
         - AwayTeam: int
         - MatchResult: pt.MatchResult
         - ThreadUrl: str
         - MatchTime: datetime (convert to UTC?)

 - Standings:
     - MatchId: int
         - UserName: str
             - Points: int

 - Predictions:
     - MatchId: int
         - UserName: str
             - Comment: str
             - CommentTime: datetime (convert to UTC?)


What if someone posts two comments?

{
    "MatchId": {
        "0": {
            "MatchWeek": 0,
            "HomeTeam": "Southampton",
            "
        }
    }
}

In [26]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [27]:
from pathlib import Path
import pandas as pd
from icecream import ic

import predthread as pt
from predthread import fbref

from collections import defaultdict
from copy import deepcopy

import pendulum

In [28]:
root = Path(".").absolute()
print(root)

/Users/julianirwin/Projects/predthread/examples/southamton_24-25_33c895d4

In [29]:
club_names = pt.club_names(root)
api_keys = pt.api_keys(root)
match_metadata = pt.match_metadata(root, match_id=0)
matches_metadata = pt.matches_metadata(root)
matches_metadata_df = pt.matches_metadata_df(root)

# ic(club_names)
# ic(match_metadata)
# ic(matches_metadata)

In [31]:
# Of last completed match
match_id = 23

In [32]:
# Using matchweek, not match id
# i_matchweek = 26
# ic(fbref.match_metadata(i_matchweek=i_matchweek))
# pt.append_match_metadata(root, fbref.match_metadata(i_matchweek))

In [33]:
pd.set_option("display.max_rows", None)
ps = pt.download_predictions(root, match_id)
ps.sort_values(["PredictedHomeGoals", "PredictedAwayGoals"], ascending=False)
# ps

,Comment,PredictedHomeGoals,PredictedAwayGoals
UserName,,,
LukeBron,4-0,4,0
Reasonable-Purple267,3-5 definitely not gonna happen but I’m trying...,3,5
nape27,3-2,3,2
Nixstricks,3-2 I hope I'm wrong and we go wild on them.,3,2
UtterlyRedditculous,3-2,3,2
3ch03d,3-1,3,1
oldredstang66,3-1,3,1
mcsgwigga,3-1,3,1
flailingpariah,3-1 and it happens again,3,1
LegitimatePass6924,3-1,3,1
JAChambel,3-0,3,0
slugmaniac,3-0,3,0
Bayne7096,2-3 saints,2,3
Boring_Inflation1494,2-3 I want a dog fight and a win goddammit,2,3
specifylength,2-2,2,2
HelpfulSloth14,2-2,2,2
Kindlydestroyed1,2-2,2,2
accidentalsalmon,2-1,2,1
strider_tom,2-1 \n\nSigh,2,1
lakermamba1999,2-1,2,1
Nas1729,2-1,2,1
jeromereyes,2-1\nhttps://youtu.be/Kou3MoGuvEM?si=_PAG8L6mL...,2,1
Zapdosman,2-1,2,1
GraveRaven,2-1,2,1
lemezier,2-1,2,1
ThatMoodyBstard,2-1,2,1
Hot_Chair_7523,2-1,2,1
pctomfor,2 - 1,2,1
Bruceplanet,2-1,2,1
uuuuuuuhhhhh,2-1,2,1
Saint_Noog,2-1. Delap punishes us,2,1
halarhala,2-0,2,0
saintstu,1-3,1,3
JimmyRiddle707,1-3,1,3
magneticacorn,"1-3, it all finally clicks",1,3
Suspicious-Living683,1-3 I can't believe I'm writing it. I'm willin...,1,3
benscott81,1-3,1,3
gradi3nt,1-2. Surely we can't lose every single game fo...,1,2
496e636f676e69746f,1-2.,1,2
fartarus,1-2,1,2
HandsomedanNZ,1-2\n\nWe finally get that sweet sweet pointage.,1,2
Positive-Sound-4972,1-1,1,1
spankeycakes,1-1,1,1
jjbc56,1-1,1,1
TheFuzzyEucalyptus,1-1,1,1
FalafelHalloumi,1-1,1,1
vibranturtle,1-1,1,1
Tough-Whereas1205,1-0,1,0
LiamBushrod,1-0,1,0
dinzil02,0-5 saints,0,5
DaisyFreakinJames,0-4 I have faith….,0,4
dan_3,0-3,0,3
whowantstogo,0-3 please just win,0,3
throwaway1throwawa,0-2 please for the love of God,0,2
DrShaftmanPhD,0-2 JURIC PARTY,0,2
Tutush,0-2. This is it \n\n^^please,0,2
Zou-KaiLi,0-1,0,1
fanea1,0-1. 92nd minute Jack Stephens header,0,1
DeadSpaceLover,0-1 Southampton. Dibling is back. #rocknroll,0,1
unbenownst,0-0,0,0

In [34]:
pt.summarize_predictions(root, match_id)

{'TotalPredictions': 60,
 'TotalHomeWinPredictions': 28,
 'TotalAwayWinPredictions': 22,
 'TotalDrawPredictions': 10}

In [35]:
new_standings = pt.calculate_updated_standings_after(root, match_id)
new_standings

,Points,PointsGained,Streak,Exacts,Corrects,Wrongs,MaxStreak
UserName,,,,,,,
Nixstricks,26,0,0,5,11,8,7
HandsomedanNZ,25,3,11,4,13,6,11
halarhala,23,0,0,3,14,5,8
fartarus,22,3,8,3,13,6,8
Saint_Noog,22,0,0,3,13,7,11
teuridge,22,0,8,2,16,5,8
flailingpariah,22,0,0,2,16,6,6
Zapdosman,20,0,0,2,14,7,7
gradi3nt,19,3,5,1,16,5,5
slugmaniac,19,0,0,3,10,4,10
jjbc56,19,0,0,2,13,7,8
LegitimatePass6924,18,0,0,3,9,6,6
specifylength,18,0,0,2,12,8,17
UtterlyRedditculous,18,0,0,1,15,6,7
benscott81,17,1,4,2,11,9,5
JAChambel,17,0,0,1,14,5,7
Boring_Inflation1494,16,1,7,1,13,5,7
magneticacorn,16,1,5,1,13,7,7
malkusm,16,0,1,2,10,11,8
Nas1729,16,0,0,2,10,3,11
MetaRift,16,0,0,1,13,8,6
GraveRaven,16,0,0,1,13,1,16
uuuuuuuhhhhh,16,0,0,0,16,8,4
JimmyRiddle707,15,1,2,1,12,10,3
NagromNitsuj,15,0,0,2,9,10,5
ThatMoodyBstard,15,0,0,1,12,8,5
TheFuzzyEucalyptus,15,0,0,0,15,7,4
strider_tom,15,0,0,0,15,7,5
Hot_Chair_7523,14,0,0,2,8,11,4
lemezier,14,0,0,1,11,11,4
mcsgwigga,14,0,0,0,14,10,5
Tutush,13,1,7,1,10,3,7
saintstu,13,1,1,1,10,12,3
Intermittent-Thinker,13,0,0,1,10,7,7
pishkabob,13,0,2,0,13,7,8
Zou-KaiLi,12,1,3,0,12,6,4
Cervix-Pounder,12,0,4,1,9,3,4
HelpfulSloth14,12,0,0,1,9,3,9
Tough-Whereas1205,12,0,0,1,9,12,3
nape27,12,0,0,0,12,9,4
Opposite_Sir1549,11,0,0,2,5,3,7
who905,11,0,3,1,8,9,3
lakermamba1999,11,0,0,1,8,2,7
hAkonf,11,0,4,0,11,5,4
dan_3,10,1,4,0,10,13,4
shontgomery,10,0,1,2,4,10,3
accidentalsalmon,10,0,0,2,4,3,8
Potato271,10,0,7,1,7,5,7
FalafelHalloumi,10,0,0,1,7,9,3
Kindlydestroyed1,10,0,0,1,7,5,7
Bruceplanet,10,0,0,1,7,11,3
oldredstang66,10,0,0,0,10,10,3
pctomfor,9,0,0,2,3,5,8
RuleBritannia1919,9,0,3,1,6,3,4
Emergency-Room-5484,9,0,1,0,9,2,4
infestationE15,9,0,1,0,9,10,2
jeromereyes,9,0,0,0,9,3,6
DrShaftmanPhD,8,1,8,2,2,3,8
kyleandrew_7,8,0,1,1,5,9,3
chebalebs,8,0,0,1,5,6,3
meteoritee,8,0,8,0,8,0,8
zoinks10,8,0,3,0,8,12,3
496e636f676e69746f,7,3,4,1,4,9,4
wostmardin,7,0,6,1,4,4,6
fcf4,7,0,1,1,4,2,5
Jpwf,7,0,0,1,4,6,3
Positive-Sound-4972,7,0,0,1,4,12,3
BlameTibor,7,0,5,0,7,2,5
MrJoshua_182,7,0,0,0,7,6,3
3ch03d,7,0,0,0,7,7,5
spankeycakes,7,0,0,0,7,12,3
LukeBron,7,0,0,0,7,3,3
Lucky_Strike1,6,0,5,1,3,5,5
madshjort,6,0,2,1,3,7,3
craig_hoxton,6,0,1,1,3,1,5
redditbanana42,6,0,0,1,3,7,3
gubbyno,6,0,5,0,6,4,5
Weary_Initiative5582,6,0,4,0,6,4,4
Klutzy-Put-1786,6,0,3,0,6,3,3
BFT_022,6,0,2,0,6,1,4
thinlike_napkins,6,0,1,0,6,2,3
CelaenaSardothien007,6,0,0,0,6,6,2
Holy_Shit_Balls_69,6,0,0,0,6,8,5
tugboet,6,0,0,0,6,8,2
DeadSpaceLover,5,1,2,0,5,6,2
Bayne7096,5,1,1,0,5,5,2
KanetsuguNaoe,5,0,5,1,2,1,5
Geralt0908,5,0,4,1,2,2,4
rghsfc,5,0,4,1,2,4,4
Henghast,5,0,4,1,2,1,4
brandonouthouse,5,0,1,1,2,5,3
vibranturtle,5,0,0,1,2,2,4
TrumpsCheetoJizz,5,0,1,0,5,3,2
FitzRoyced,5,0,0,0,5,4,2
thatcrazyhorse,5,0,0,0,5,5,2
Relevant_Rev,5,0,0,0,5,10,2
saint-86,5,0,0,0,5,3,2
Suspicious-Living683,4,1,4,0,4,0,4
JoshHQ,4,0,4,1,1,0,4
Stealthsonger,4,0,4,1,1,1,4
SirFrancisBenali,4,0,4,1,1,0,4
PM_ME_YOUR_MARS_BARS,4,0,0,1,1,3,4
rapsin4lmao,4,0,0,1,1,1,4
GordonRamsayGhost,4,0,3,0,4,1,3
Many_Background_3679,4,0,3,0,4,2,3
aredditusername69,4,0,2,0,4,4,2
NorwegianSaint,4,0,1,0,4,4,2
Kindlydestroyed,4,0,0,0,4,2,2
hahs95,4,0,0,0,4,4,2
MangerDanger1,4,0,0,0,4,6,2
BJH19,4,0,0,0,4,10,1
whowantstogo,3,1,1,0,3,17,1
StreetSuspicious8456,3,0,3,1,0,0,3
HOWDY__YALL,3,0,3,1,0,0,3
TheTyrantis,3,0,3,1,0,0,3
Deadpooldan,3,0,3,1,0,0,3
fozz555,3,0,3,1,0,0,3
PickaxeJunky,3,0,3,1,0,0,3
SomeGuyCalledPercy,3,0,0,1,0,1,3
uKrayZ,3,0,0,1,0,1,3
Scared_Leading2875,3,0,3,0,3,0,3
T_Hr0,3,0,3,0,3,0,3
Revolutionary_Cup602,3,0,2,0,3,1,2
delegod1,3,0,2,0,3,3,2
mdubyo,3,0,2,0,3,2,2
LordOrtus,3,0,2,0,3,3,2
exhaleair,3,0,1,0,3,4,2
jackodriscol,3,0,0,0,3,2,3
fanea1,2,1,2,0,2,0,2
dinzil02,2,1,2,0,2,1,2
throwaway1throwawa,2,1,1,0,2,7,1
Zstupple,2,0,2,0,2,0,2
Anglo-fornian,2,0,2,0,2,2,2
Likunandi,2,0,2,0,2,0,2
Lost_Disk,2,0,2,0,2,3,2
buddyomg,2,0,2,0,2,0,2
igsey,2,0,2,0,2,0,2
Squm9,2,0,2,0,2,1,2
K-E-N-07,2,0,2,0,2,0,2
generic-username0123,2,0,2,0,2,0,2
PhilipRobertson,2,0,1,0,2,2,1
GuteLord-,2,0,1,0,2,2,1
gedly89,2,0,1,0,2,4,1
BanjoPants74,2,0,1,0,2,1,1
Beardedmetalhead,2,0,1,0,2,1,1
BevvyTime,2,0,1,0,2,1,1
Alina2017,2,0,1,0,2,2,1
jayforplay,2,0,0,0,2,2,1
bendezhashein,2,0,0,0,2,1,2
Desperate_Low9482,2,0,0,0,2,5,1
Tspecs05,2,0,0,0,2,7,2
Weirdo_boy02,2,0,0,0,2,4,1
Zakedawn,2,0,0,0,2,4,2
kempston_joystick,2,0,0,0,2,4,2
LovingCatholicPriest,2,0,0,0,2,2,2
Hefty-Competition297,2,0,0,0,2,18,1
Antidote-Killer,2,0,0,0,2,13,1
Reasonable-Purple267,1,1,1,0,1,2,1
DaisyFreakinJames,1,1,1,0,1,0,1
FluidSaint,1,0,1,0,1,0,1
Finoptics,1,0,1,0,1,0,1
mr_grission,1,0,1,0,1,0,1
KingHarpoon616,1,0,1,0,1,0,1
chesterchugger,1,0,1,0,1,0,1
3rd__i,1,0,1,0,1,3,1
baristaboy24,1,0,1,0,1,1,1
bathtub_not_beach,1,0,1,0,1,1,1
Fast-Engineer915,1,0,1,0,1,1,1
Wafflz__,1,0,1,0,1,0,1
galaxygalaxy777,1,0,1,0,1,0,1
Captain_Obvious_x,1,0,1,0,1,1,1
Fatty4forks,1,0,1,0,1,0,1
rabbitradar,1,0,1,0,1,2,1
TouristDramatic8295,1,0,1,0,1,1,1
kevmccartney,1,0,1,0,1,1,1
SoggyMattress2,1,0,1,0,1,0,1
boondocksaint08,1,0,1,0,1,0,1
OpScreechingHalt,1,0,1,0,1,0,1
Educational_Ad288,1,0,1,0,1,0,1
No_Amphibian6382,1,0,1,0,1,0,1
ThermoWizz,1,0,1,0,1,0,1
GuyInWessex,1,0,1,0,1,0,1
Patentlyy,1,0,1,0,1,1,1
JoeGordon07,1,0,1,0,1,1,1
ShadowedEclipse,1,0,1,0,1,0,1
InfernoTurnip,1,0,1,0,1,0,1
matt_rev,1,0,1,0,1,3,1
Spirited_Ad_2697,1,0,1,0,1,0,1
Expensive_Elk_466,1,0,1,0,1,0,1
CatDadFurrever,1,0,1,0,1,0,1
LocationThin4587,1,0,1,0,1,0,1
Temujins_here,1,0,1,0,1,0,1
NickB76,1,0,1,0,1,0,1
istarisaints,1,0,1,0,1,2,1
Extreme-Sport-5772,1,0,1,0,1,0,1
lewwwwwwwwwwwiscook,1,0,1,0,1,0,1
akarmandoug,1,0,1,0,1,0,1
JonhyWonder123,1,0,1,0,1,0,1
openworldganes898,1,0,1,0,1,0,1
jonnyhoots,1,0,1,0,1,2,1
shirleyspike44,1,0,1,0,1,0,1
BritishDrummer,1,0,1,0,1,0,1
wigl301,1,0,1,0,1,0,1
inertia7245,1,0,1,0,1,0,1
Menulem,1,0,1,0,1,0,1
Lation,1,0,1,0,1,0,1
Ecstatic-West-8587,1,0,1,0,1,0,1
thewalrus-,1,0,1,0,1,0,1
sadsouthamptonfan,1,0,1,0,1,0,1
BrotherBrother94,1,0,1,0,1,0,1
Federal_Ad_5898,1,0,1,0,1,2,1
wheresmywifeuk,1,0,1,0,1,0,1
Adz087087,1,0,1,0,1,0,1
Salt-Cup-2300,1,0,0,0,1,3,1
Blackgotham-12,1,0,0,0,1,2,1
Toast_for_President,1,0,0,0,1,1,1
asdaf22,1,0,0,0,1,1,1
Adziboy,1,0,0,0,1,2,1
fluffyplayery,1,0,0,0,1,1,1
Ahegaopizza,1,0,0,0,1,2,1
thisisclassicus,1,0,0,0,1,2,1
J_Dymond,1,0,0,0,1,4,1
allbarneynorubble,1,0,0,0,1,3,1
Financial-Glass5693,1,0,0,0,1,2,1
parabola9999,1,0,0,0,1,1,1
master_shifwho,1,0,0,0,1,5,1
whattodotodo8,1,0,0,0,1,11,1
NC9-,1,0,0,0,1,1,1
jakeyboy723,1,0,0,0,1,2,1
GrandmasterYoda1,1,0,0,0,1,8,1
BlueInq,1,0,0,0,1,3,1
alki07,0,0,0,0,0,1,0
MAFIAxMaverick,0,0,0,0,0,4,0
gooffking,0,0,0,0,0,2,0
roberthart327,0,0,0,0,0,1,0
darave123,0,0,0,0,0,4,0
Unlucky_Island_742,0,0,0,0,0,2,0
Vsovs,0,0,0,0,0,1,0
WaltertheWobot,0,0,0,0,0,2,0
happysnappygoat,0,0,0,0,0,1,0
frooberts,0,0,0,0,0,1,0
K3GGY,0,0,0,0,0,1,0
Dr-Honks,0,0,0,0,0,2,0
EntersMikers,0,0,0,0,0,1,0
MrRyan1320,0,0,0,0,0,2,0
sgm94,0,0,0,0,0,3,0
guillotine-jones,0,0,0,0,0,2,0
Super-saints12,0,0,0,0,0,1,0
TheEggMan45,0,0,0,0,0,1,0
gongasf,0,0,0,0,0,2,0
jrdn1616,0,0,0,0,0,2,0
bundy554,0,0,0,0,0,1,0
Whenthebeatdropolis,0,0,0,0,0,1,0
street--donut,0,0,0,0,0,1,0
Glittering-Cow-4702,0,0,0,0,0,1,0
Potential-Oil-1795,0,0,0,0,0,1,0
soverign_cheese,0,0,0,0,0,1,0
BigTettenator,0,0,0,0,0,2,0
West_Equivalent7997,0,0,0,0,0,1,0
MonarchyBoner,0,0,0,0,0,1,0
Cormac419,0,0,0,0,0,1,0
King_Lamb,0,0,0,0,0,1,0
PunnyIsNotFunny,0,0,0,0,0,1,0
weatherghost,0,0,0,0,0,1,0
Nervous_Jaguar_2826,0,0,0,0,0,2,0
JoeBiggzDC,0,0,0,0,0,1,0
LiveFree-603,0,0,0,0,0,1,0
TheHatThatTalks,0,0,0,0,0,1,0
Top_Dirt2557,0,0,0,0,0,1,0
Notional-,0,0,0,0,0,1,0
BrandonPol,0,0,0,0,0,1,0
Singh255,0,0,0,0,0,1,0
King_PieNan,0,0,0,0,0,2,0
Ok_Mix_3544,0,0,0,0,0,2,0
Mr_Yellow_Trousers,0,0,0,0,0,4,0
Magmar18,0,0,0,0,0,1,0
neil2252,0,0,0,0,0,1,0
No_Wrap_9979,0,0,0,0,0,1,0
FromTheEdgeOfTheDeep,0,0,0,0,0,2,0
Jamez_XIX,0,0,0,0,0,1,0
Evening-Tart3067,0,0,0,0,0,1,0
mbridge2610,0,0,0,0,0,2,0
senorbellend17,0,0,0,0,0,1,0
No_Pound5513,0,0,0,0,0,1,0
HorusHeresay,0,0,0,0,0,1,0
GreedoVision,0,0,0,0,0,1,0
TheSpitfires,0,0,0,0,0,1,0
fl0ralp,0,0,0,0,0,2,0
Adventurous_Bass_673,0,0,0,0,0,1,0
YourWeekendDad,0,0,0,0,0,1,0
rigill,0,0,0,0,0,1,0
nmc1995,0,0,0,0,0,1,0
Same-Temporary8468,0,0,0,0,0,1,0
Crazymorsejr,0,0,0,0,0,1,0
MerryRain,0,0,0,0,0,2,0
Special_Tune9184,0,0,0,0,0,1,0
slashmpw,0,0,0,0,0,1,0
Harris_vs,0,0,0,0,0,1,0
benjwilliam,0,0,0,0,0,1,0
Stix-Zadupya,0,0,0,0,0,1,0
RevengeofSudz,0,0,0,0,0,2,0
cameronastonmartin,0,0,0,0,0,1,0
Grumblepiglet,0,0,0,0,0,1,0
rndltr,0,0,0,0,0,1,0
FleetCasual,0,0,0,0,0,1,0
mooseday,0,0,0,0,0,1,0
Local-Record7707,0,0,0,0,0,1,0
SpecificAlgae5594,0,0,0,0,0,1,0
tommypopz,0,0,0,0,0,1,0
OakieDoker,0,0,0,0,0,1,0
abseykebabsy,0,0,0,0,0,1,0
TehEv0,0,0,0,0,0,1,0
vitinaly,0,0,0,0,0,1,0
DylanAB07,0,0,0,0,0,1,0
Cleatmr,0,0,0,0,0,1,0
Lumpy-Indication,0,0,0,0,0,2,0
-Xero,0,0,0,0,0,1,0
JolliJarhead,0,0,0,0,0,1,0
j_karamazov,0,0,0,0,0,2,0
nfoneo,0,0,0,0,0,1,0
Haaave-You-Met-Ted,0,0,0,0,0,1,0
jerifishnisshin,0,0,0,0,0,1,0
unbenownst,0,0,0,0,0,1,0
LiamBushrod,0,0,0,0,0,1,0

In [36]:
print(new_standings.reset_index().to_markdown())

|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | Nixstricks           |       26 |              0 |        0 |        5 |         11 |        8 |           7 |
|   1 | HandsomedanNZ        |       25 |              3 |       11 |        4 |         13 |        6 |          11 |
|   2 | halarhala            |       23 |              0 |        0 |        3 |         14 |        5 |           8 |
|   3 | fartarus             |       22 |              3 |        8 |        3 |         13 |        6 |           8 |
|   4 | Saint_Noog           |       22 |              0 |        0 |        3 |         13 |        7 |          11 |
|   5 | teuridge             |       22 |              0 |        8 |        2 |         16 |        5 |           8 |
|   6 | flailingpariah       |       22 |              0 |        0 |        2 |         16 |        6 |           6 |
|   7 | Zapdosman            |       20 |              0 |        0 |        2 |         14 |        7 |           7 |
|   8 | gradi3nt             |       19 |              3 |        5 |        1 |         16 |        5 |           5 |
|   9 | slugmaniac           |       19 |              0 |        0 |        3 |         10 |        4 |          10 |
|  10 | jjbc56               |       19 |              0 |        0 |        2 |         13 |        7 |           8 |
|  11 | LegitimatePass6924   |       18 |              0 |        0 |        3 |          9 |        6 |           6 |
|  12 | specifylength        |       18 |              0 |        0 |        2 |         12 |        8 |          17 |
|  13 | UtterlyRedditculous  |       18 |              0 |        0 |        1 |         15 |        6 |           7 |
|  14 | benscott81           |       17 |              1 |        4 |        2 |         11 |        9 |           5 |
|  15 | JAChambel            |       17 |              0 |        0 |        1 |         14 |        5 |           7 |
|  16 | Boring_Inflation1494 |       16 |              1 |        7 |        1 |         13 |        5 |           7 |
|  17 | magneticacorn        |       16 |              1 |        5 |        1 |         13 |        7 |           7 |
|  18 | malkusm              |       16 |              0 |        1 |        2 |         10 |       11 |           8 |
|  19 | Nas1729              |       16 |              0 |        0 |        2 |         10 |        3 |          11 |
|  20 | MetaRift             |       16 |              0 |        0 |        1 |         13 |        8 |           6 |
|  21 | GraveRaven           |       16 |              0 |        0 |        1 |         13 |        1 |          16 |
|  22 | uuuuuuuhhhhh         |       16 |              0 |        0 |        0 |         16 |        8 |           4 |
|  23 | JimmyRiddle707       |       15 |              1 |        2 |        1 |         12 |       10 |           3 |
|  24 | NagromNitsuj         |       15 |              0 |        0 |        2 |          9 |       10 |           5 |
|  25 | ThatMoodyBstard      |       15 |              0 |        0 |        1 |         12 |        8 |           5 |
|  26 | TheFuzzyEucalyptus   |       15 |              0 |        0 |        0 |         15 |        7 |           4 |
|  27 | strider_tom          |       15 |              0 |        0 |        0 |         15 |        7 |           5 |
|  28 | Hot_Chair_7523       |       14 |              0 |        0 |        2 |          8 |       11 |           4 |
|  29 | lemezier             |       14 |              0 |        0 |        1 |         11 |       11 |           4 |
|  30 | mcsgwigga            |       14 |              0 |        0 |        0 |         14 |       10 |           5 |
|  31 | Tutush               |       13 |              1 |        7 |        1 |         10 |        3 |           7 |
|  32 | saintstu             |       13 |              1 |        1 |        1 |         10 |       12 |           3 |
|  33 | Intermittent-Thinker |       13 |              0 |        0 |        1 |         10 |        7 |           7 |
|  34 | pishkabob            |       13 |              0 |        2 |        0 |         13 |        7 |           8 |
|  35 | Zou-KaiLi            |       12 |              1 |        3 |        0 |         12 |        6 |           4 |
|  36 | Cervix-Pounder       |       12 |              0 |        4 |        1 |          9 |        3 |           4 |
|  37 | HelpfulSloth14       |       12 |              0 |        0 |        1 |          9 |        3 |           9 |
|  38 | Tough-Whereas1205    |       12 |              0 |        0 |        1 |          9 |       12 |           3 |
|  39 | nape27               |       12 |              0 |        0 |        0 |         12 |        9 |           4 |
|  40 | Opposite_Sir1549     |       11 |              0 |        0 |        2 |          5 |        3 |           7 |
|  41 | who905               |       11 |              0 |        3 |        1 |          8 |        9 |           3 |
|  42 | lakermamba1999       |       11 |              0 |        0 |        1 |          8 |        2 |           7 |
|  43 | hAkonf               |       11 |              0 |        4 |        0 |         11 |        5 |           4 |
|  44 | dan_3                |       10 |              1 |        4 |        0 |         10 |       13 |           4 |
|  45 | shontgomery          |       10 |              0 |        1 |        2 |          4 |       10 |           3 |
|  46 | accidentalsalmon     |       10 |              0 |        0 |        2 |          4 |        3 |           8 |
|  47 | Potato271            |       10 |              0 |        7 |        1 |          7 |        5 |           7 |
|  48 | FalafelHalloumi      |       10 |              0 |        0 |        1 |          7 |        9 |           3 |
|  49 | Kindlydestroyed1     |       10 |              0 |        0 |        1 |          7 |        5 |           7 |
|  50 | Bruceplanet          |       10 |              0 |        0 |        1 |          7 |       11 |           3 |
|  51 | oldredstang66        |       10 |              0 |        0 |        0 |         10 |       10 |           3 |
|  52 | pctomfor             |        9 |              0 |        0 |        2 |          3 |        5 |           8 |
|  53 | RuleBritannia1919    |        9 |              0 |        3 |        1 |          6 |        3 |           4 |
|  54 | Emergency-Room-5484  |        9 |              0 |        1 |        0 |          9 |        2 |           4 |
|  55 | infestationE15       |        9 |              0 |        1 |        0 |          9 |       10 |           2 |
|  56 | jeromereyes          |        9 |              0 |        0 |        0 |          9 |        3 |           6 |
|  57 | DrShaftmanPhD        |        8 |              1 |        8 |        2 |          2 |        3 |           8 |
|  58 | kyleandrew_7         |        8 |              0 |        1 |        1 |          5 |        9 |           3 |
|  59 | chebalebs            |        8 |              0 |        0 |        1 |          5 |        6 |           3 |
|  60 | meteoritee           |        8 |              0 |        8 |        0 |          8 |        0 |           8 |
|  61 | zoinks10             |        8 |              0 |        3 |        0 |          8 |       12 |           3 |
|  62 | 496e636f676e69746f   |        7 |              3 |        4 |        1 |          4 |        9 |           4 |
|  63 | wostmardin           |        7 |              0 |        6 |        1 |          4 |        4 |           6 |
|  64 | fcf4                 |        7 |              0 |        1 |        1 |          4 |        2 |           5 |
|  65 | Jpwf                 |        7 |              0 |        0 |        1 |          4 |        6 |           3 |
|  66 | Positive-Sound-4972  |        7 |              0 |        0 |        1 |          4 |       12 |           3 |
|  67 | BlameTibor           |        7 |              0 |        5 |        0 |          7 |        2 |           5 |
|  68 | MrJoshua_182         |        7 |              0 |        0 |        0 |          7 |        6 |           3 |
|  69 | 3ch03d               |        7 |              0 |        0 |        0 |          7 |        7 |           5 |
|  70 | spankeycakes         |        7 |              0 |        0 |        0 |          7 |       12 |           3 |
|  71 | LukeBron             |        7 |              0 |        0 |        0 |          7 |        3 |           3 |
|  72 | Lucky_Strike1        |        6 |              0 |        5 |        1 |          3 |        5 |           5 |
|  73 | madshjort            |        6 |              0 |        2 |        1 |          3 |        7 |           3 |
|  74 | craig_hoxton         |        6 |              0 |        1 |        1 |          3 |        1 |           5 |
|  75 | redditbanana42       |        6 |              0 |        0 |        1 |          3 |        7 |           3 |
|  76 | gubbyno              |        6 |              0 |        5 |        0 |          6 |        4 |           5 |
|  77 | Weary_Initiative5582 |        6 |              0 |        4 |        0 |          6 |        4 |           4 |
|  78 | Klutzy-Put-1786      |        6 |              0 |        3 |        0 |          6 |        3 |           3 |
|  79 | BFT_022              |        6 |              0 |        2 |        0 |          6 |        1 |           4 |
|  80 | thinlike_napkins     |        6 |              0 |        1 |        0 |          6 |        2 |           3 |
|  81 | CelaenaSardothien007 |        6 |              0 |        0 |        0 |          6 |        6 |           2 |
|  82 | Holy_Shit_Balls_69   |        6 |              0 |        0 |        0 |          6 |        8 |           5 |
|  83 | tugboet              |        6 |              0 |        0 |        0 |          6 |        8 |           2 |
|  84 | DeadSpaceLover       |        5 |              1 |        2 |        0 |          5 |        6 |           2 |
|  85 | Bayne7096            |        5 |              1 |        1 |        0 |          5 |        5 |           2 |
|  86 | KanetsuguNaoe        |        5 |              0 |        5 |        1 |          2 |        1 |           5 |
|  87 | Geralt0908           |        5 |              0 |        4 |        1 |          2 |        2 |           4 |
|  88 | rghsfc               |        5 |              0 |        4 |        1 |          2 |        4 |           4 |
|  89 | Henghast             |        5 |              0 |        4 |        1 |          2 |        1 |           4 |
|  90 | brandonouthouse      |        5 |              0 |        1 |        1 |          2 |        5 |           3 |
|  91 | vibranturtle         |        5 |              0 |        0 |        1 |          2 |        2 |           4 |
|  92 | TrumpsCheetoJizz     |        5 |              0 |        1 |        0 |          5 |        3 |           2 |
|  93 | FitzRoyced           |        5 |              0 |        0 |        0 |          5 |        4 |           2 |
|  94 | thatcrazyhorse       |        5 |              0 |        0 |        0 |          5 |        5 |           2 |
|  95 | Relevant_Rev         |        5 |              0 |        0 |        0 |          5 |       10 |           2 |
|  96 | saint-86             |        5 |              0 |        0 |        0 |          5 |        3 |           2 |
|  97 | Suspicious-Living683 |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  98 | JoshHQ               |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
|  99 | Stealthsonger        |        4 |              0 |        4 |        1 |          1 |        1 |           4 |
| 100 | SirFrancisBenali     |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
| 101 | PM_ME_YOUR_MARS_BARS |        4 |              0 |        0 |        1 |          1 |        3 |           4 |
| 102 | rapsin4lmao          |        4 |              0 |        0 |        1 |          1 |        1 |           4 |
| 103 | GordonRamsayGhost    |        4 |              0 |        3 |        0 |          4 |        1 |           3 |
| 104 | Many_Background_3679 |        4 |              0 |        3 |        0 |          4 |        2 |           3 |
| 105 | aredditusername69    |        4 |              0 |        2 |        0 |          4 |        4 |           2 |
| 106 | NorwegianSaint       |        4 |              0 |        1 |        0 |          4 |        4 |           2 |
| 107 | Kindlydestroyed      |        4 |              0 |        0 |        0 |          4 |        2 |           2 |
| 108 | hahs95               |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
| 109 | MangerDanger1        |        4 |              0 |        0 |        0 |          4 |        6 |           2 |
| 110 | BJH19                |        4 |              0 |        0 |        0 |          4 |       10 |           1 |
| 111 | whowantstogo         |        3 |              1 |        1 |        0 |          3 |       17 |           1 |
| 112 | StreetSuspicious8456 |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 113 | HOWDY__YALL          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 114 | TheTyrantis          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 115 | Deadpooldan          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 116 | fozz555              |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 117 | PickaxeJunky         |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 118 | SomeGuyCalledPercy   |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
| 119 | uKrayZ               |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
| 120 | Scared_Leading2875   |        3 |              0 |        3 |        0 |          3 |        0 |           3 |
| 121 | T_Hr0                |        3 |              0 |        3 |        0 |          3 |        0 |           3 |
| 122 | Revolutionary_Cup602 |        3 |              0 |        2 |        0 |          3 |        1 |           2 |
| 123 | delegod1             |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
| 124 | mdubyo               |        3 |              0 |        2 |        0 |          3 |        2 |           2 |
| 125 | LordOrtus            |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
| 126 | exhaleair            |        3 |              0 |        1 |        0 |          3 |        4 |           2 |
| 127 | jackodriscol         |        3 |              0 |        0 |        0 |          3 |        2 |           3 |
| 128 | fanea1               |        2 |              1 |        2 |        0 |          2 |        0 |           2 |
| 129 | dinzil02             |        2 |              1 |        2 |        0 |          2 |        1 |           2 |
| 130 | throwaway1throwawa   |        2 |              1 |        1 |        0 |          2 |        7 |           1 |
| 131 | Zstupple             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 132 | Anglo-fornian        |        2 |              0 |        2 |        0 |          2 |        2 |           2 |
| 133 | Likunandi            |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 134 | Lost_Disk            |        2 |              0 |        2 |        0 |          2 |        3 |           2 |
| 135 | buddyomg             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 136 | igsey                |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 137 | Squm9                |        2 |              0 |        2 |        0 |          2 |        1 |           2 |
| 138 | K-E-N-07             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 139 | generic-username0123 |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 140 | PhilipRobertson      |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 141 | GuteLord-            |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 142 | gedly89              |        2 |              0 |        1 |        0 |          2 |        4 |           1 |
| 143 | BanjoPants74         |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 144 | Beardedmetalhead     |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 145 | BevvyTime            |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 146 | Alina2017            |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 147 | jayforplay           |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
| 148 | bendezhashein        |        2 |              0 |        0 |        0 |          2 |        1 |           2 |
| 149 | Desperate_Low9482    |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
| 150 | Tspecs05             |        2 |              0 |        0 |        0 |          2 |        7 |           2 |
| 151 | Weirdo_boy02         |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
| 152 | Zakedawn             |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 153 | kempston_joystick    |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 154 | LovingCatholicPriest |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
| 155 | Hefty-Competition297 |        2 |              0 |        0 |        0 |          2 |       18 |           1 |
| 156 | Antidote-Killer      |        2 |              0 |        0 |        0 |          2 |       13 |           1 |
| 157 | Reasonable-Purple267 |        1 |              1 |        1 |        0 |          1 |        2 |           1 |
| 158 | DaisyFreakinJames    |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
| 159 | FluidSaint           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 160 | Finoptics            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 161 | mr_grission          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 162 | KingHarpoon616       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 163 | chesterchugger       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 164 | 3rd__i               |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 165 | baristaboy24         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |

In [20]:
predictions = pt.load_predictions(root, match_id)
old_standings = pt.load_standings_after(root, match_id - 1)
new_standings_p = pt.load_standings_after(root, match_id)
new_standings_p = new_standings.rename(columns=lambda x: x + "*")
predictions.join(old_standings, new_standings_p)

KeyError:                       Points*  PointsGained*  Streak*  Exacts*  Corrects*  \
UserName
Nixstricks                 25              1        5        5         10
halarhala                  23              1        2        3         14
teuridge                   21              1        7        2         15
flailingpariah             21              1        4        2         15
Zapdosman                  19              1        6        2         13
HandsomedanNZ              19              1        5        2         13
Saint_Noog                 19              1        3        2         13
slugmaniac                 19              0       10        3         10
jjbc56                     18              3        4        2         12
LegitimatePass6924         18              0        3        3          9
specifylength              18              0        0        2         12
UtterlyRedditculous        17              1        6        1         14
MetaRift                   16              1        5        1         13
JAChambel                  16              1        4        1         13
fartarus                   16              1        2        1         13
gradi3nt                   16              1        2        0         16
Nas1729                    16              0       11        2         10
NagromNitsuj               15              1        4        2          9
benscott81                 15              1        2        2          9
GraveRaven                 15              1       15        1         12
uuuuuuuhhhhh               15              1        3        0         15
malkusm                    15              0        0        2          9
ThatMoodyBstard            14              1        4        1         11
magneticacorn              14              1        3        1         11
strider_tom                14              1        4        0         14
TheFuzzyEucalyptus         14              1        3        0         14
lemezier                   13              1        3        1         10
mcsgwigga                  13              1        4        0         13
Hot_Chair_7523             13              0        3        2          7
Intermittent-Thinker       13              0        0        1         10
JimmyRiddle707             13              0        0        1         10
Boring_Inflation1494       12              1        3        0         12
saintstu                   12              0        0        1          9
pishkabob                  12              0        1        0         12
Tutush                     11              1        5        1          8
Cervix-Pounder             11              1        3        1          8
HelpfulSloth14             11              1        1        1          8
nape27                     11              1        3        0         11
Opposite_Sir1549           11              0        0        2          5
lakermamba1999             11              0        7        1          8
who905                     11              0        3        1          8
Kindlydestroyed1           10              1        2        1          7
hAkonf                     10              1        3        0         10
Zou-KaiLi                  10              1        1        0         10
shontgomery                10              0        1        2          4
Potato271                  10              0        7        1          7
FalafelHalloumi            10              0        2        1          7
Bruceplanet                 9              1        1        1          6
oldredstang66               9              1        2        0          9
pctomfor                    9              0        1        2          3
RuleBritannia1919           9              0        3        1          6
Emergency-Room-5484         9              0        1        0          9
infestationE15              9              0        1        0          9
Tough-Whereas1205           9              0        0        0          9
dan_3                       8              1        2        0          8
kyleandrew_7                8              0        1        1          5
chebalebs                   8              0        0        1          5
meteoritee                  8              0        8        0          8
jeromereyes                 8              0        1        0          8
wostmardin                  7              1        6        1          4
accidentalsalmon            7              1        5        1          4
BlameTibor                  7              1        5        0          7
zoinks10                    7              1        2        0          7
MrJoshua_182                7              1        1        0          7
3ch03d                      7              1        1        0          7
DrShaftmanPhD               7              0        7        2          1
fcf4                        7              0        1        1          4
Jpwf                        7              0        0        1          4
Positive-Sound-4972         7              0        0        1          4
gubbyno                     6              1        5        0          6
Klutzy-Put-1786             6              1        3        0          6
LukeBron                    6              1        2        0          6
Lucky_Strike1               6              0        5        1          3
madshjort                   6              0        2        1          3
craig_hoxton                6              0        1        1          3
redditbanana42              6              0        0        1          3
BFT_022                     6              0        2        0          6
thinlike_napkins            6              0        1        0          6
spankeycakes                6              0        1        0          6
CelaenaSardothien007        6              0        0        0          6
Holy_Shit_Balls_69          6              0        0        0          6
tugboet                     6              0        0        0          6
Weary_Initiative5582        5              1        3        0          5
KanetsuguNaoe               5              0        5        1          2
Geralt0908                  5              0        4        1          2
vibranturtle                5              0        4        1          2
rghsfc                      5              0        4        1          2
FitzRoyced                  5              0        0        0          5
thatcrazyhorse              5              0        0        0          5
Relevant_Rev                5              0        0        0          5
saint-86                    5              0        0        0          5
Many_Background_3679        4              1        3        0          4
Bayne7096                   4              1        1        0          4
JoshHQ                      4              0        4        1          1
Stealthsonger               4              0        4        1          1
SirFrancisBenali            4              0        4        1          1
PM_ME_YOUR_MARS_BARS        4              0        0        1          1
rapsin4lmao                 4              0        0        1          1
brandonouthouse             4              0        0        1          1
GordonRamsayGhost           4              0        3        0          4
aredditusername69           4              0        2        0          4
496e636f676e69746f          4              0        1        0          4
Kindlydestroyed             4              0        0        0          4
hahs95                      4              0        0        0          4
MangerDanger1               4              0        0        0          4
BJH19                       4              0        0        0          4
TrumpsCheetoJizz            4              0        0        0          4
Scared_Leading2875          3              1        3        0          3
T_Hr0                       3              1        3        0          3
StreetSuspicious8456        3              0        3        1          0
HOWDY__YALL                 3              0        3        1          0
TheTyrantis                 3              0        3        1          0
Deadpooldan                 3              0        3        1          0
fozz555                     3              0        3        1          0
PickaxeJunky                3              0        3        1          0
SomeGuyCalledPercy          3              0        0        1          0
uKrayZ                      3              0        0        1          0
Suspicious-Living683        3              0        3        0          3
Revolutionary_Cup602        3              0        2        0          3
delegod1                    3              0        2        0          3
mdubyo                      3              0        2        0          3
LordOrtus                   3              0        2        0          3
exhaleair                   3              0        1        0          3
jackodriscol                3              0        0        0          3
NorwegianSaint              3              0        0        0          3
DeadSpaceLover              3              0        0        0          3
Zstupple                    2              0        2        0          2
Anglo-fornian               2              0        2        0          2
Likunandi                   2              0        2        0          2
Lost_Disk                   2              0        2        0          2
buddyomg                    2              0        2        0          2
igsey                       2              0        2        0          2
Squm9                       2              0        2        0          2
K-E-N-07                    2              0        2        0          2
generic-username0123        2              0        2        0          2
PhilipRobertson             2              0        1        0          2
GuteLord-                   2              0        1        0          2
gedly89                     2              0        1        0          2
BanjoPants74                2              0        1        0          2
Beardedmetalhead            2              0        1        0          2
BevvyTime                   2              0        1        0          2
Alina2017                   2              0        1        0          2
Henghast                    2              0        1        0          2
jayforplay                  2              0        0        0          2
bendezhashein               2              0        0        0          2
Desperate_Low9482           2              0        0        0          2
Tspecs05                    2              0        0        0          2
Weirdo_boy02                2              0        0        0          2
Zakedawn                    2              0        0        0          2
kempston_joystick           2              0        0        0          2
LovingCatholicPriest        2              0        0        0          2
Hefty-Competition297        2              0        0        0          2
whowantstogo                2              0        0        0          2
Antidote-Killer             2              0        0        0          2
dinzil02                    1              1        1        0          1
thewalrus-                  1              1        1        0          1
sadsouthamptonfan           1              1        1        0          1
BrotherBrother94            1              1        1        0          1
FluidSaint                  1              0        1        0          1
Finoptics                   1              0        1        0          1
mr_grission                 1              0        1        0          1
KingHarpoon616              1              0        1        0          1
chesterchugger              1              0        1        0          1
3rd__i                      1              0        1        0          1
baristaboy24                1              0        1        0          1
bathtub_not_beach           1              0        1        0          1
Fast-Engineer915            1              0        1        0          1
Wafflz__                    1              0        1        0          1
galaxygalaxy777             1              0        1        0          1
Captain_Obvious_x           1              0        1        0          1
Fatty4forks                 1              0        1        0          1
rabbitradar                 1              0        1        0          1
TouristDramatic8295         1              0        1        0          1
kevmccartney                1              0        1        0          1
SoggyMattress2              1              0        1        0          1
boondocksaint08             1              0        1        0          1
OpScreechingHalt            1              0        1        0          1
Educational_Ad288           1              0        1        0          1
No_Amphibian6382            1              0        1        0          1
ThermoWizz                  1              0        1        0          1
GuyInWessex                 1              0        1        0          1
Patentlyy                   1              0        1        0          1
JoeGordon07                 1              0        1        0          1
fanea1                      1              0        1        0          1
ShadowedEclipse             1              0        1        0          1
InfernoTurnip               1              0        1        0          1
matt_rev                    1              0        1        0          1
Spirited_Ad_2697            1              0        1        0          1
Expensive_Elk_466           1              0        1        0          1
CatDadFurrever              1              0        1        0          1
LocationThin4587            1              0        1        0          1
Temujins_here               1              0        1        0          1
NickB76                     1              0        1        0          1
istarisaints                1              0        1        0          1
Extreme-Sport-5772          1              0        1        0          1
lewwwwwwwwwwwiscook         1              0        1        0          1
akarmandoug                 1              0        1        0          1
JonhyWonder123              1              0        1        0          1
openworldganes898           1              0        1        0          1
jonnyhoots                  1              0        1        0          1
shirleyspike44              1              0        1        0          1
BritishDrummer              1              0        1        0          1
wigl301                     1              0        1        0          1
inertia7245                 1              0        1        0          1
Menulem                     1              0        1        0          1
Lation                      1              0        1        0          1
Ecstatic-West-8587          1              0        1        0          1
Salt-Cup-2300               1              0        0        0          1
Blackgotham-12              1              0        0        0          1
Toast_for_President         1              0        0        0          1
asdaf22                     1              0        0        0          1
Adziboy                     1              0        0        0          1
fluffyplayery               1              0        0        0          1
Ahegaopizza                 1              0        0        0          1
thisisclassicus             1              0        0        0          1
J_Dymond                    1              0        0        0          1
allbarneynorubble           1              0        0        0          1
Financial-Glass5693         1              0        0        0          1
parabola9999                1              0        0        0          1
master_shifwho              1              0        0        0          1
whattodotodo8               1              0        0        0          1
NC9-                        1              0        0        0          1
jakeyboy723                 1              0        0        0          1
GrandmasterYoda1            1              0        0        0          1
throwaway1throwawa          1              0        0        0          1
BlueInq                     1              0        0        0          1
alki07                      0              0        0        0          0
MAFIAxMaverick              0              0        0        0          0
gooffking                   0              0        0        0          0
roberthart327               0              0        0        0          0
darave123                   0              0        0        0          0
Unlucky_Island_742          0              0        0        0          0
Vsovs                       0              0        0        0          0
WaltertheWobot              0              0        0        0          0
happysnappygoat             0              0        0        0          0
frooberts                   0              0        0        0          0
K3GGY                       0              0        0        0          0
Dr-Honks                    0              0        0        0          0
EntersMikers                0              0        0        0          0
MrRyan1320                  0              0        0        0          0
sgm94                       0              0        0        0          0
guillotine-jones            0              0        0        0          0
Super-saints12              0              0        0        0          0
TheEggMan45                 0              0        0        0          0
gongasf                     0              0        0        0          0
jrdn1616                    0              0        0        0          0
bundy554                    0              0        0        0          0
Whenthebeatdropolis         0              0        0        0          0
street--donut               0              0        0        0          0
Glittering-Cow-4702         0              0        0        0          0
Potential-Oil-1795          0              0        0        0          0
soverign_cheese             0              0        0        0          0
BigTettenator               0              0        0        0          0
West_Equivalent7997         0              0        0        0          0
MonarchyBoner               0              0        0        0          0
Cormac419                   0              0        0        0          0
King_Lamb                   0              0        0        0          0
PunnyIsNotFunny             0              0        0        0          0
weatherghost                0              0        0        0          0
Nervous_Jaguar_2826         0              0        0        0          0
JoeBiggzDC                  0              0        0        0          0
LiveFree-603                0              0        0        0          0
TheHatThatTalks             0              0        0        0          0
Top_Dirt2557                0              0        0        0          0
Notional-                   0              0        0        0          0
BrandonPol                  0              0        0        0          0
Singh255                    0              0        0        0          0
King_PieNan                 0              0        0        0          0

In [37]:
pt.summarize_standings_after(root, match_id)

{'TotalExacts': 4, 'TotalCorrects': 18}

# Post Template

## Todo

 - Add callouts for exacts and streaks

In [38]:
m_next = pt.match_metadata(root, match_id+1)
m_last = pt.match_metadata(root, match_id)

s_pred = pt.summarize_predictions(root, match_id - 1)
s_stand = pt.summarize_standings_after(root, match_id-1)

# Parse the ISO 8601 date string into a pendulum datetime object
uk_time = pendulum.parse(m_next["MatchTimeUtc"]).in_tz('Europe/London')
human_readable_date = uk_time.format('dddd, MMMM D, YYYY HH:mm:ss')

print(f"""
# Prediction Thread Match {match_id + 2}: {m_next["HomeClub"]} vs {m_next["AwayClub"]}

{human_readable_date}

# Home - Away Format

 - Home: {m_next["HomeClub"]}
 - Away: {m_next["AwayClub"]}

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match ({m_last["HomeClub"]} - {m_last["AwayClub"]})

{m_last["ThreadUrl"]}

 - Total Predictions: {s_pred["TotalPredictions"]}
 - Predicted Home Wins: {s_pred["TotalHomeWinPredictions"]} 
 - Predicted Away Wins: {s_pred["TotalAwayWinPredictions"]} 
 - Predicted Draws: {s_pred["TotalDrawPredictions"]}
 - Exacts: {s_stand["TotalExacts"]}
 - Corrects: {s_stand["TotalCorrects"]} 

# Standings
{new_standings.reset_index().to_markdown()}
""")

# Prediction Thread Match 25: Southampton vs Bournemouth

Saturday, February 15, 2025 15:00:00

# Home - Away Format

 - Home: Southampton
 - Away: Bournemouth

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match (Ipswich Town - Southampton)

https://www.reddit.com/r/SaintsFC/comments/1ierjpt/comment/macf4c9/?context=3

 - Total Predictions: 65
 - Predicted Home Wins: 11
 - Predicted Away Wins: 48
 - Predicted Draws: 6
 - Exacts: 7
 - Corrects: 41

# Standings
|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | Nixstricks           |       26 |              0 |        0 |        5 |         11 |        8 |           7 |
|   1 | HandsomedanNZ        |       25 |              3 |       11 |        4 |         13 |        6 |          11 |
|   2 | halarhala            |       23 |              0 |        0 |        3 |         14 |        5 |           8 |
|   3 | fartarus             |       22 |              3 |        8 |        3 |         13 |        6 |           8 |
|   4 | Saint_Noog           |       22 |              0 |        0 |        3 |         13 |        7 |          11 |
|   5 | teuridge             |       22 |              0 |        8 |        2 |         16 |        5 |           8 |
|   6 | flailingpariah       |       22 |              0 |        0 |        2 |         16 |        6 |           6 |
|   7 | Zapdosman            |       20 |              0 |        0 |        2 |         14 |        7 |           7 |
|   8 | gradi3nt             |       19 |              3 |        5 |        1 |         16 |        5 |           5 |
|   9 | slugmaniac           |       19 |              0 |        0 |        3 |         10 |        4 |          10 |
|  10 | jjbc56               |       19 |              0 |        0 |        2 |         13 |        7 |           8 |
|  11 | LegitimatePass6924   |       18 |              0 |        0 |        3 |          9 |        6 |           6 |
|  12 | specifylength        |       18 |              0 |        0 |        2 |         12 |        8 |          17 |
|  13 | UtterlyRedditculous  |       18 |              0 |        0 |        1 |         15 |        6 |           7 |
|  14 | benscott81           |       17 |              1 |        4 |        2 |         11 |        9 |           5 |
|  15 | JAChambel            |       17 |              0 |        0 |        1 |         14 |        5 |           7 |
|  16 | Boring_Inflation1494 |       16 |              1 |        7 |        1 |         13 |        5 |           7 |
|  17 | magneticacorn        |       16 |              1 |        5 |        1 |         13 |        7 |           7 |
|  18 | malkusm              |       16 |              0 |        1 |        2 |         10 |       11 |           8 |
|  19 | Nas1729              |       16 |              0 |        0 |        2 |         10 |        3 |          11 |
|  20 | MetaRift             |       16 |              0 |        0 |        1 |         13 |        8 |           6 |
|  21 | GraveRaven           |       16 |              0 |        0 |        1 |         13 |        1 |          16 |
|  22 | uuuuuuuhhhhh         |       16 |              0 |        0 |        0 |         16 |        8 |           4 |
|  23 | JimmyRiddle707       |       15 |              1 |        2 |        1 |         12 |       10 |           3 |
|  24 | NagromNitsuj         |       15 |              0 |        0 |        2 |          9 |       10 |           5 |
|  25 | ThatMoodyBstard      |       15 |              0 |        0 |        1 |         12 |        8 |           5 |
|  26 | TheFuzzyEucalyptus   |       15 |              0 |        0 |        0 |         15 |        7 |           4 |
|  27 | strider_tom          |       15 |              0 |        0 |        0 |         15 |        7 |           5 |
|  28 | Hot_Chair_7523       |       14 |              0 |        0 |        2 |          8 |       11 |           4 |
|  29 | lemezier             |       14 |              0 |        0 |        1 |         11 |       11 |           4 |
|  30 | mcsgwigga            |       14 |              0 |        0 |        0 |         14 |       10 |           5 |
|  31 | Tutush               |       13 |              1 |        7 |        1 |         10 |        3 |           7 |
|  32 | saintstu             |       13 |              1 |        1 |        1 |         10 |       12 |           3 |
|  33 | Intermittent-Thinker |       13 |              0 |        0 |        1 |         10 |        7 |           7 |
|  34 | pishkabob            |       13 |              0 |        2 |        0 |         13 |        7 |           8 |
|  35 | Zou-KaiLi            |       12 |              1 |        3 |        0 |         12 |        6 |           4 |
|  36 | Cervix-Pounder       |       12 |              0 |        4 |        1 |          9 |        3 |           4 |
|  37 | HelpfulSloth14       |       12 |              0 |        0 |        1 |          9 |        3 |           9 |
|  38 | Tough-Whereas1205    |       12 |              0 |        0 |        1 |          9 |       12 |           3 |
|  39 | nape27               |       12 |              0 |        0 |        0 |         12 |        9 |           4 |
|  40 | Opposite_Sir1549     |       11 |              0 |        0 |        2 |          5 |        3 |           7 |
|  41 | who905               |       11 |              0 |        3 |        1 |          8 |        9 |           3 |
|  42 | lakermamba1999       |       11 |              0 |        0 |        1 |          8 |        2 |           7 |
|  43 | hAkonf               |       11 |              0 |        4 |        0 |         11 |        5 |           4 |
|  44 | dan_3                |       10 |              1 |        4 |        0 |         10 |       13 |           4 |
|  45 | shontgomery          |       10 |              0 |        1 |        2 |          4 |       10 |           3 |
|  46 | accidentalsalmon     |       10 |              0 |        0 |        2 |          4 |        3 |           8 |
|  47 | Potato271            |       10 |              0 |        7 |        1 |          7 |        5 |           7 |
|  48 | FalafelHalloumi      |       10 |              0 |        0 |        1 |          7 |        9 |           3 |
|  49 | Kindlydestroyed1     |       10 |              0 |        0 |        1 |          7 |        5 |           7 |
|  50 | Bruceplanet          |       10 |              0 |        0 |        1 |          7 |       11 |           3 |
|  51 | oldredstang66        |       10 |              0 |        0 |        0 |         10 |       10 |           3 |
|  52 | pctomfor             |        9 |              0 |        0 |        2 |          3 |        5 |           8 |
|  53 | RuleBritannia1919    |        9 |              0 |        3 |        1 |          6 |        3 |           4 |
|  54 | Emergency-Room-5484  |        9 |              0 |        1 |        0 |          9 |        2 |           4 |
|  55 | infestationE15       |        9 |              0 |        1 |        0 |          9 |       10 |           2 |
|  56 | jeromereyes          |        9 |              0 |        0 |        0 |          9 |        3 |           6 |
|  57 | DrShaftmanPhD        |        8 |              1 |        8 |        2 |          2 |        3 |           8 |
|  58 | kyleandrew_7         |        8 |              0 |        1 |        1 |          5 |        9 |           3 |
|  59 | chebalebs            |        8 |              0 |        0 |        1 |          5 |        6 |           3 |
|  60 | meteoritee           |        8 |              0 |        8 |        0 |          8 |        0 |           8 |
|  61 | zoinks10             |        8 |              0 |        3 |        0 |          8 |       12 |           3 |
|  62 | 496e636f676e69746f   |        7 |              3 |        4 |        1 |          4 |        9 |           4 |
|  63 | wostmardin           |        7 |              0 |        6 |        1 |          4 |        4 |           6 |
|  64 | fcf4                 |        7 |              0 |        1 |        1 |          4 |        2 |           5 |
|  65 | Jpwf                 |        7 |              0 |        0 |        1 |          4 |        6 |           3 |
|  66 | Positive-Sound-4972  |        7 |              0 |        0 |        1 |          4 |       12 |           3 |
|  67 | BlameTibor           |        7 |              0 |        5 |        0 |          7 |        2 |           5 |
|  68 | MrJoshua_182         |        7 |              0 |        0 |        0 |          7 |        6 |           3 |
|  69 | 3ch03d               |        7 |              0 |        0 |        0 |          7 |        7 |           5 |
|  70 | spankeycakes         |        7 |              0 |        0 |        0 |          7 |       12 |           3 |
|  71 | LukeBron             |        7 |              0 |        0 |        0 |          7 |        3 |           3 |
|  72 | Lucky_Strike1        |        6 |              0 |        5 |        1 |          3 |        5 |           5 |
|  73 | madshjort            |        6 |              0 |        2 |        1 |          3 |        7 |           3 |
|  74 | craig_hoxton         |        6 |              0 |        1 |        1 |          3 |        1 |           5 |
|  75 | redditbanana42       |        6 |              0 |        0 |        1 |          3 |        7 |           3 |
|  76 | gubbyno              |        6 |              0 |        5 |        0 |          6 |        4 |           5 |
|  77 | Weary_Initiative5582 |        6 |              0 |        4 |        0 |          6 |        4 |           4 |
|  78 | Klutzy-Put-1786      |        6 |              0 |        3 |        0 |          6 |        3 |           3 |
|  79 | BFT_022              |        6 |              0 |        2 |        0 |          6 |        1 |           4 |
|  80 | thinlike_napkins     |        6 |              0 |        1 |        0 |          6 |        2 |           3 |
|  81 | CelaenaSardothien007 |        6 |              0 |        0 |        0 |          6 |        6 |           2 |
|  82 | Holy_Shit_Balls_69   |        6 |              0 |        0 |        0 |          6 |        8 |           5 |
|  83 | tugboet              |        6 |              0 |        0 |        0 |          6 |        8 |           2 |
|  84 | DeadSpaceLover       |        5 |              1 |        2 |        0 |          5 |        6 |           2 |
|  85 | Bayne7096            |        5 |              1 |        1 |        0 |          5 |        5 |           2 |
|  86 | KanetsuguNaoe        |        5 |              0 |        5 |        1 |          2 |        1 |           5 |
|  87 | Geralt0908           |        5 |              0 |        4 |        1 |          2 |        2 |           4 |
|  88 | rghsfc               |        5 |              0 |        4 |        1 |          2 |        4 |           4 |
|  89 | Henghast             |        5 |              0 |        4 |        1 |          2 |        1 |           4 |
|  90 | brandonouthouse      |        5 |              0 |        1 |        1 |          2 |        5 |           3 |
|  91 | vibranturtle         |        5 |              0 |        0 |        1 |          2 |        2 |           4 |
|  92 | TrumpsCheetoJizz     |        5 |              0 |        1 |        0 |          5 |        3 |           2 |
|  93 | FitzRoyced           |        5 |              0 |        0 |        0 |          5 |        4 |           2 |
|  94 | thatcrazyhorse       |        5 |              0 |        0 |        0 |          5 |        5 |           2 |
|  95 | Relevant_Rev         |        5 |              0 |        0 |        0 |          5 |       10 |           2 |
|  96 | saint-86             |        5 |              0 |        0 |        0 |          5 |        3 |           2 |
|  97 | Suspicious-Living683 |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  98 | JoshHQ               |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
|  99 | Stealthsonger        |        4 |              0 |        4 |        1 |          1 |        1 |           4 |
| 100 | SirFrancisBenali     |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
| 101 | PM_ME_YOUR_MARS_BARS |        4 |              0 |        0 |        1 |          1 |        3 |           4 |
| 102 | rapsin4lmao          |        4 |              0 |        0 |        1 |          1 |        1 |           4 |
| 103 | GordonRamsayGhost    |        4 |              0 |        3 |        0 |          4 |        1 |           3 |
| 104 | Many_Background_3679 |        4 |              0 |        3 |        0 |          4 |        2 |           3 |
| 105 | aredditusername69    |        4 |              0 |        2 |        0 |          4 |        4 |           2 |
| 106 | NorwegianSaint       |        4 |              0 |        1 |        0 |          4 |        4 |           2 |
| 107 | Kindlydestroyed      |        4 |              0 |        0 |        0 |          4 |        2 |           2 |
| 108 | hahs95               |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
| 109 | MangerDanger1        |        4 |              0 |        0 |        0 |          4 |        6 |           2 |
| 110 | BJH19                |        4 |              0 |        0 |        0 |          4 |       10 |           1 |
| 111 | whowantstogo         |        3 |              1 |        1 |        0 |          3 |       17 |           1 |
| 112 | StreetSuspicious8456 |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 113 | HOWDY__YALL          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 114 | TheTyrantis          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 115 | Deadpooldan          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 116 | fozz555              |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 117 | PickaxeJunky         |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
| 118 | SomeGuyCalledPercy   |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
| 119 | uKrayZ               |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
| 120 | Scared_Leading2875   |        3 |              0 |        3 |        0 |          3 |        0 |           3 |
| 121 | T_Hr0                |        3 |              0 |        3 |        0 |          3 |        0 |           3 |
| 122 | Revolutionary_Cup602 |        3 |              0 |        2 |        0 |          3 |        1 |           2 |
| 123 | delegod1             |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
| 124 | mdubyo               |        3 |              0 |        2 |        0 |          3 |        2 |           2 |
| 125 | LordOrtus            |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
| 126 | exhaleair            |        3 |              0 |        1 |        0 |          3 |        4 |           2 |
| 127 | jackodriscol         |        3 |              0 |        0 |        0 |          3 |        2 |           3 |
| 128 | fanea1               |        2 |              1 |        2 |        0 |          2 |        0 |           2 |
| 129 | dinzil02             |        2 |              1 |        2 |        0 |          2 |        1 |           2 |
| 130 | throwaway1throwawa   |        2 |              1 |        1 |        0 |          2 |        7 |           1 |
| 131 | Zstupple             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 132 | Anglo-fornian        |        2 |              0 |        2 |        0 |          2 |        2 |           2 |
| 133 | Likunandi            |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 134 | Lost_Disk            |        2 |              0 |        2 |        0 |          2 |        3 |           2 |
| 135 | buddyomg             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 136 | igsey                |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 137 | Squm9                |        2 |              0 |        2 |        0 |          2 |        1 |           2 |
| 138 | K-E-N-07             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 139 | generic-username0123 |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
| 140 | PhilipRobertson      |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 141 | GuteLord-            |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 142 | gedly89              |        2 |              0 |        1 |        0 |          2 |        4 |           1 |
| 143 | BanjoPants74         |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 144 | Beardedmetalhead     |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 145 | BevvyTime            |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 146 | Alina2017            |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 147 | jayforplay           |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
| 148 | bendezhashein        |        2 |              0 |        0 |        0 |          2 |        1 |           2 |
| 149 | Desperate_Low9482    |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
| 150 | Tspecs05             |        2 |              0 |        0 |        0 |          2 |        7 |           2 |
| 151 | Weirdo_boy02         |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
| 152 | Zakedawn             |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 153 | kempston_joystick    |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 154 | LovingCatholicPriest |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
| 155 | Hefty-Competition297 |        2 |              0 |        0 |        0 |          2 |       18 |           1 |
| 156 | Antidote-Killer      |        2 |              0 |        0 |        0 |          2 |       13 |           1 |
| 157 | Reasonable-Purple267 |        1 |              1 |        1 |        0 |          1 |        2 |           1 |